n_arms: 5
m_fidelity: 2
fidelity_bounds:
  - 0.1
  - 0.0
costs:
  - 0.5
  - 5.0
arms:
  - - 0.4
    - 0.5
  - - 0.4
    - 0.5
  - - 0.4
    - 0.5
  - - 0.4
    - 0.5
  - - 0.5
    - 0.6
dist_type: gaussian
other_fixed_dist_param: 0.1