n_arms: 4
m_fidelity: 5
fidelity_bounds:
  - 0.1
  - 0.08
  - 0.04
  - 0.02
  - 0.0
costs:
  - 0.1
  - 0.125
  - 0.25
  - 0.5
  - 1.0
arms:
  - - 0.41
    - 0.45
    - 0.47
    - 0.48
    - 0.5
  - - 0.35
    - 0.37
    - 0.38
    - 0.36
    - 0.35
  - - 0.51
    - 0.56
    - 0.64
    - 0.62
    - 0.61
  - - 0.41
    - 0.39
    - 0.4
    - 0.42
    - 0.43
dist_type: gaussian
other_fixed_dist_param: 0.1